final String about =
    "Сочетаю традиционные элементы общепризнанной системы специальной физической подготовки и свои индивидуальные наработки. Восстанавливаю связочный аппарат бойцов и спортсменов игровых видов спорта после травм.\n\nДаю методики на развитие периферического зрения с использованием таблиц Шульте, Горбова, корректурных проб Бурдона.\n\nПрименяю в своей методике тесты на внимательность, практические упражнения для активизации работы центральной нервной системы, упражнения способствующие интеграции нейронной сети в обоих полушариях головного мозга, и использую методы одновременного выполнения нескольких задач с изменением обстановки.\n\nДанные методики являются приобретённым опытом многолетней тренерской и исследовательской деятельности.\n\nДаю специальную подготовку, чтобы спортсмен был лучше в своём спорте, и общую подготовку, чтобы спортсмен был здоровым, сильным, чтобы улучшать свой уровень.\n\nНаходясь в потоке, я стимулирую определённые мышцы, которые не задействованы в основном виде деятельности.  Использование знаний в гимнастике, позволяет мне работать с весом собственного тела, потому что такие упражнения идеальны для центральной нервной системы.\n\nЯ считаю, что обучение нужно адаптировать под конкретную личность, не используя общепринятую систему подготовки спортсменов высшей категории.";

final String aboutEn =
    "I combine traditional elements of the universally recognized system of special physical training and my own individual developments. I restore the ligamentous apparatus of fighters and athletes of team sports after injuries.\n\nI give methods for the development of peripheral vision using the tables of Schulte, Gorbov, Bourdon's correction tests.\n\nI use attentiveness tests in my methodology, practical exercises to activate the work of the central nervous system, exercises that promote the integration of the neural network in both hemispheres of the brain, and use methods for simultaneously performing several tasks with a change in the situation.\n\nThese techniques are the acquired experience of many years of coaching and research activities.\n\nI give special training so that the athlete is better in his sport, and general training so that the athlete is healthy, strong, in order to improve his level.\n\nBeing in the flow, I stimulate certain muscles that are not involved in the main activity. Using knowledge in gymnastics allows me to work with my own body weight, because such exercises are ideal for the central nervous system\n\nЯ считаю, что обучение нужно адаптировать под конкретную личность, не используя общепринятую систему подготовки спортсменов высшей категории.";

final String founder =
    "Буздов Артур Юрьевич\n\nСпециалист в области общей и специальной физической подготовки, гимнастики, растяжки и IQ подготовки, координации движений, развитии мозговой деятельности профессиональных бойцов ММА, и спортсменов игровых видов спорта\n\nЗащитил кандидатскую диссертацию по педагогическим наукам 28 апреля 2009 года, имеет учёное звание – кандидата педагогических наук с 18.12.2009 г, и учёную степень доцента с 16.07.2015 г., научно-педагогический стаж составляет 18 лет.\n\nИмею 50 научных публикаций, в том числе, участие в четырех международных конференциях. Являюсь соавтором восьми учебно-методических пособий, и двенадцати электронных учебников и рацпредложений\n\nОпыт тренерской работы 29 лет\n\nСистематически повышаю свою квалификацию. В 2016 году прошел повышение квалификации в «Национальном государственном Университете физической культуры, спорта и здоровья имени П.Ф. Лесгафта, Санкт-Петербург».\n\nЯвляюсь тренером по спортивной гимнастике, рукопашному бою и регби -13. Подготовил восемь мастеров спорта по рукопашному бою, 18 КМС, 54 спортсмена первого разряда, трёх мастеров спорта по спортивной гимнастике, и 35 КМС по регби-13";

final String founderEn =
    "Buzdov Artur Yurievich\n\nSpecialist in the field of general and special physical training, gymnastics, stretching and IQ training, coordination of movements, development of brain activity of professional MMA fighters and team sports athletes\n\nHe defended his thesis in pedagogical sciences on April 28, 2009, has an academic title - candidate of pedagogical sciences since 12/18/2009, and an associate professor degree since 07/16/2015, scientific and pedagogical experience is 18 years\n\nI have 50 scientific publications, including participation in four international conferences. I am a co-author of eight teaching aids, and twelve electronic textbooks and rationalization proposals\n\n29 years of coaching experience\n\nI systematically improve my skills. In 2016, he underwent advanced training at the National State University of Physical Culture, Sports and Health named after P.F. Lesgaft, St. Petersburg.\n\nI am a coach in gymnastics, hand-to-hand combat and rugby -13. Trained eight masters of sports in hand-to-hand combat, 18 CCM, 54 first-class athletes, three masters of sports in gymnastics, and 35 CCM in rugby-13";
